flowchart LR
    %% =========================
    %% Stage 1: Data Input
    %% =========================
    subgraph S1["Stage 1: Data Input"]
        direction LR
        A("fa:fa-code Code(01_simulate_data.Rmd)")
        B("fa:fa-database Simulate data")
        C[("fa:fa-table raw_sleep_data.rds")]
    end

    %% =========================
    %% Stage 2: Data Processing
    %% =========================
    subgraph S2["Stage 2: Data Processing"]
        direction LR
        D("fa:fa-code Code
            (02_processing_and_cleaning.Rmd)")
        E("fa:fa-broom Data cleaning and processing")
        F[("fa:fa-table clean_sleep_data.rds")]
        
    end

    %% =========================
    %% Stage 3: Data Analysis
    %% =========================
    subgraph S3["Stage 3: Data Analysis"]
        direction LR
        G("fa:fa-code Code 
         (03_exploratory_analysis.Rmd)")
        H("fa:fa-chart-line Data analysis")
        I("fa:fa-file-alt Outputs")
    end

    %% =========================
    %% Connections
    %% =========================
    A --> B --> C --> D --> E --> F --> G --> H --> I
    E --> F

    %% =========================
    %% Styling (visual emphasis)
    %% =========================
    style A fill:#2962FF, stroke:#2962FF, color:#FFFFFF
    style D fill:#00C853, stroke:#00C853, color:#FFFFFF
    style G fill:#AA00FF, stroke:#AA00FF, color:#FFFFFF
    style I fill:#FF6D00, stroke:#FF6D00, color:#FFFFFF